# Generated by Django 4.2.6 on 2023-10-17 02:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_Profesion', models.CharField(max_length=255)),
                ('profesion_created_at', models.DateTimeField(auto_now_add=True)),
                ('profesion_updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Profesion',
                'verbose_name_plural': 'Profesiones',
            },
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docente_tipo_Id', models.CharField(max_length=10)),
                ('docente_estado', models.BooleanField()),
                ('docente_numero_Id', models.CharField(max_length=50)),
                ('docente_fecha_nacim', models.DateField()),
                ('docente_created_at', models.DateTimeField(auto_now_add=True)),
                ('docente_updated_at', models.DateTimeField(auto_now=True)),
                ('docente_profesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppUsuarios.profesion', verbose_name='Profesion')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Docente',
                'verbose_name_plural': 'Docentes',
            },
        ),
    ]
