# Generated by Django 4.2.6 on 2023-10-17 02:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AppUsuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docente',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='UsuarioDocente'),
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estudiante_fecha_matricula', models.DateField()),
                ('estudiante_estado', models.BooleanField()),
                ('estudiante_tipo_Id', models.CharField(max_length=10)),
                ('estudiante_numero_Id', models.CharField(max_length=50)),
                ('estudiante_fecha_nac', models.DateField()),
                ('estudiante_created_at', models.DateTimeField(auto_now_add=True)),
                ('estudiante_updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='UsuarioEstudiante')),
            ],
            options={
                'verbose_name': 'Estudiante',
                'verbose_name_plural': 'Esudiantes',
            },
        ),
    ]
