# Generated by Django 4.2.6 on 2023-12-04 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppUsuarios', '0003_participante'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='curso',
            field=models.CharField(default=22, max_length=50),
            preserve_default=False,
        ),
    ]
