# Generated by Django 4.2.6 on 2023-12-04 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppUsuarios', '0004_estudiante_curso'),
    ]

    operations = [
        migrations.AddField(
            model_name='participante',
            name='curso',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
