# Generated by Django 4.2.6 on 2024-03-24 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppAsistencia', '0005_matricula_and_more'),
        ('AppUsuarios', '0005_participante_curso'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Participante',
        ),
    ]
