# Generated by Django 4.2.6 on 2023-10-28 04:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppUsuarios', '0003_participante'),
        ('AppAsistencia', '0002_observacionesestudiante_observacionparticipantes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistenciaestudiante',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppUsuarios.estudiante'),
        ),
        migrations.AlterField(
            model_name='asistenciaparticipante',
            name='Participante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppUsuarios.participante'),
        ),
        migrations.AlterField(
            model_name='horario',
            name='hora_fin',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='horario',
            name='hora_inicio',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='observacionesestudiante',
            name='asistenciaEst',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppAsistencia.asistenciaestudiante'),
        ),
        migrations.AlterField(
            model_name='observacionparticipantes',
            name='asistenciaPart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppAsistencia.asistenciaparticipante'),
        ),
    ]
