# Generated by Django 4.2.6 on 2023-10-28 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppAsistencia', '0003_alter_asistenciaestudiante_estudiante_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asistenciaparticipante',
            old_name='Participante',
            new_name='participante',
        ),
        migrations.AlterField(
            model_name='asistenciaestudiante',
            name='soporte',
            field=models.ImageField(default='Sin registro', null=True, upload_to='imageSoportes/'),
        ),
    ]
