# Generated by Django 4.2.6 on 2024-03-24 04:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppUsuarios', '0005_participante_curso'),
        ('AppAsistencia', '0004_rename_participante_asistenciaparticipante_participante_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppAsistencia.curso')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppUsuarios.estudiante')),
            ],
        ),
        migrations.RemoveField(
            model_name='observacionparticipantes',
            name='asistenciaPart',
        ),
        migrations.RemoveField(
            model_name='asistenciaestudiante',
            name='curso',
        ),
        migrations.RemoveField(
            model_name='asistenciaestudiante',
            name='estudiante',
        ),
        migrations.DeleteModel(
            name='AsistenciaParticipante',
        ),
        migrations.DeleteModel(
            name='ObservacionParticipantes',
        ),
        migrations.AddField(
            model_name='asistenciaestudiante',
            name='matricula_estudiante',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='AppAsistencia.matricula'),
            preserve_default=False,
        ),
    ]
