# Generated by Django 4.2.6 on 2024-04-17 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppAsistencia', '0010_remove_curso_materia_remove_curso_periodo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cursomateria',
            options={'verbose_name': 'Curso Materia', 'verbose_name_plural': 'Cursos Materias'},
        ),
        migrations.AlterField(
            model_name='matricula',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppAsistencia.cursomateria'),
        ),
    ]
