# Generated by Django 4.2.6 on 2024-04-17 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppAsistencia', '0011_alter_cursomateria_options_alter_matricula_curso'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matricula',
            old_name='curso',
            new_name='curso_Materia',
        ),
    ]
