# Generated by Django 5.0.4 on 2024-05-05 22:22

import AppAsistencia.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppAsistencia', '0012_rename_curso_matricula_curso_materia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistenciaestudiante',
            name='soporte',
            field=models.ImageField(null=True, upload_to=AppAsistencia.models.soporte_file_path),
        ),
    ]
